from geopy.geocoders import Nominatim
nom = Nominatim()
n = nom.geocode('Россия, Санкт-Петербург, Орбели, 27 к6')
print(n.latitude, n.longitude)
n = nom.geocode('Россия, Санкт-Петербург, ул Орбели, 27 к6')
print(n.latitude, n.longitude)
n = nom.geocode('Россия, Санкт-Петербург,улица Орбели, 27 к6')
print(n.latitude, n.longitude)
n = nom.geocode('Санкт-Петербург,улица Орбели, 27 к6')
print(n.latitude, n.longitude)
n = nom.geocode('СПб,улица Орбели, 27 к6')
print(n.latitude, n.longitude)
n = nom.geocode('Орбели, 27 к6')
print(n.latitude, n.longitude)